#!/bin/bash

# AIME MLC - Machine Learning Container Management 
# 
# Copyright (c) AIME GmbH and affiliates. Find more info at https://www.aime.info/mlc 
# 
# This software may be used and distributed according to the terms of the MIT LICENSE 

# Save all arguments in a variable
all_args=$@
# Obtain the location of the mlc file
MLC_PATH=$(dirname $0)

# Pass the arguments to the Python script
python3 "$MLC_PATH/mlc.py" $all_args


